apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "${CRON_SCHEDULE}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: "${CRON_IMAGE}"
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure