name: Testing this workflow 
on:
  push:
    branches:
      - dev
      - main 
  workflow_dispatch:

jobs:
  sample-run:
    runs-on: [self-hosted,macos]
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.ref_name }}
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: print secrets from environment 
        run: |
          echo "${{ secrets.NAME }}" >> secret.txt
      
      - name: Testing environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
             echo "DEV_ACR_URL=satydev.azurecr.io" >> $GITHUB_ENV
          else
             echo "NONPROD_ACR_URL=satynonprod.azurecr.io" >> $GITHUB_ENV
          fi
      - name: Printing acr names
        run: |
          echo "${{ env.DEV_ACR_URL }}" >> devacr.txt
          echo "${{ env.NONPROD_ACR_URL }}" >> nonprodacr.txt
      - name: Run kubernetes cron job 
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
             echo "CRON_SCHEDULE=*/5 * * * *" >> $GITHUB_ENV
             echo "CRON_IMAGE=${{ env.DEV_ACR_URL }}/dev-cron-job:latest"
          else
             echo "CRON_SCHEDULE=*/3 * * * *" >> $GITHUB_ENV
             echo "CRON_IMAGE=${{ env.NONPROD_ACR_URL }}/nonprod-cron-job:latest"
          fi
      - name: Apply cron job
        run: |
          envsubst < TestCronJob.yml | kubectl apply -f -
          env: 
            CRON_SCHEDULE: ${{ env.CRON_SCHEDULE }}
            CRON_IMAGE: ${{ env.CRON_IMAGE }}



      