name: Testing this workflow
on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  sample-run:
    runs-on: [self-hosted, macos]
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.ref_name }}
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print secrets from environment
        run: |
          echo "${{ secrets.NAME }}" >> secret.txt
      
      - name: Set ACR URL based on branch
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "DEV_ACR_URL=satydev.azurecr.io" >> $GITHUB_ENV
          else
            echo "NONPROD_ACR_URL=satynonprod.azurecr.io" >> $GITHUB_ENV
          fi

      - name: Print ACR names
        run: |
          echo "DEV_ACR_URL=${{ env.DEV_ACR_URL }}"
          echo "NONPROD_ACR_URL=${{ env.NONPROD_ACR_URL }}"

      - name: Set CronJob environment variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "CRON_SCHEDULE=*/5 * * * *" >> $GITHUB_ENV
            echo "CRON_IMAGE=${{ env.DEV_ACR_URL }}/dev-cron-job:latest" >> $GITHUB_ENV
          else
            echo "CRON_SCHEDULE=*/3 * * * *" >> $GITHUB_ENV
            echo "CRON_IMAGE=${{ env.NONPROD_ACR_URL }}/nonprod-cron-job:latest" >> $GITHUB_ENV
          fi

      - name: Apply Kubernetes CronJob
        run: |
          envsubst < ./TestCronJob.yml | kubectl apply -f -
        env:
          CRON_SCHEDULE: ${{ env.CRON_SCHEDULE }}
          CRON_IMAGE: ${{ env.CRON_IMAGE }}
